//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define IDI_ICON1                       1

#define IDR_PRESET_DEFAULT 200
#define IDR_PRESET_FANATEC_CSL_DD__GT_DD_PRO 201
#define IDR_PRESET_FANATEC_PODIUM_DD1DD2 202
#define IDR_PRESET_GM___YAW_KICK_DD_21_NM__MOZA_R21_ULTRA_ 203
#define IDR_PRESET_GM_DD_21_NM__MOZA_R21_ULTRA_ 204
#define IDR_PRESET_GT3_DD_15_NM__SIMAGIC_ALPHA_ 205
#define IDR_PRESET_GUIDE_BRAKING_LOCKUP 206
#define IDR_PRESET_GUIDE_GYROSCOPIC_DAMPING 207
#define IDR_PRESET_GUIDE_OVERSTEER__REAR_GRIP_ 208
#define IDR_PRESET_GUIDE_SLIDE_TEXTURE__SCRUB_ 209
#define IDR_PRESET_GUIDE_SOP_YAW__KICK_ 210
#define IDR_PRESET_GUIDE_TRACTION_LOSS__SPIN_ 211
#define IDR_PRESET_GUIDE_UNDERSTEER__FRONT_GRIP_ 212
#define IDR_PRESET_LMPXHY_DD_15_NM__SIMAGIC_ALPHA_ 213
#define IDR_PRESET_LOGITECH_G25G27G29G920 214
#define IDR_PRESET_MOZA_R5R9R16R21 215
#define IDR_PRESET_SIMAGIC_ALPHAALPHA_MINIALPHA_U 216
#define IDR_PRESET_SIMUCUBE_2_SPORTPROULTIMATE 217
#define IDR_PRESET_T300_V0_7_164 218
#define IDR_PRESET_TEST_GAME_BASE_FFB_ONLY 219
#define IDR_PRESET_TEST_NO_EFFECTS 220
#define IDR_PRESET_TEST_REAR_ALIGN_TORQUE_ONLY 221
#define IDR_PRESET_TEST_SLIDE_TEXTURE_ONLY 222
#define IDR_PRESET_TEST_SOP_BASE_ONLY 223
#define IDR_PRESET_TEST_SOP_ONLY 224
#define IDR_PRESET_TEST_TEXTURES_ONLY 225
#define IDR_PRESET_TEST_UNDERSTEER_ONLY 226
#define IDR_PRESET_TEST_YAW_KICK_ONLY 227
#define IDR_PRESET_THRUSTMASTER_T_GTT_GT_II 228
#define IDR_PRESET_THRUSTMASTER_T300TX 229
#define IDR_PRESET_THRUSTMASTER_TS_PCTS_XW 230

#define IDR_PRESET_FIRST IDR_PRESET_DEFAULT
#define IDR_PRESET_LAST  IDR_PRESET_THRUSTMASTER_TS_PCTS_XW

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
