app_version = '0.7.221'
name = 'MyPreset'

[Advanced]
aux_telemetry_reconstruction = 0
gyro_gain = 0.0
gyro_smoothing = 0.0
rest_api_enabled = false
rest_api_port = 6397
road_fallback_scale = 0.05000000074505806
soft_lock_damping = 0.5
soft_lock_enabled = true
soft_lock_stiffness = 20.0
speed_gate_lower = 1.0
speed_gate_upper = 5.0
stationary_damping = 1.0
understeer_affects_sop = false

[Braking]
abs_freq = 25.5
abs_gain = 2.0
abs_pulse_enabled = false
brake_load_cap = 2.0
lockup_bump_reject = 0.10000000149011612
lockup_enabled = true
lockup_freq_scale = 1.0199999809265137
lockup_full_pct = 5.0
lockup_gain = 0.3747900128364563
lockup_gamma = 0.10000000149011612
lockup_prediction_sens = 10.0
lockup_rear_boost = 10.0
lockup_start_pct = 1.0

[FrontAxle]
flatspot_strength = 1.0
flatspot_suppression = false
ingame_ffb_gain = 1.0
notch_q = 2.0
static_notch_enabled = false
static_notch_freq = 11.0
static_notch_width = 2.0
steering_100hz_reconstruction = 0
steering_shaft_gain = 1.0
steering_shaft_smoothing = 0.0
torque_passthrough = false
torque_source = 0
understeer_effect = 1.0
understeer_gamma = 1.0

[General]
auto_load_normalization_enabled = false
dynamic_normalization_enabled = false
gain = 1.0
min_force = 0.0
target_rim_nm = 10.0
wheelbase_max_nm = 15.0

[GripEstimation]
chassis_inertia_smoothing = 0.0
grip_smoothing_fast = 0.004999999888241291
grip_smoothing_sensitivity = 0.10000000149011612
grip_smoothing_steady = 0.05000000074505806
load_sensitivity_enabled = true
optimal_slip_angle = 0.10000000149011612
optimal_slip_ratio = 0.11999999731779099
slip_angle_smoothing = 0.0020000000949949026

[LoadForces]
lat_load_effect = 0.0
lat_load_transform = 0
long_load_effect = 0.0
long_load_smoothing = 0.15000000596046448
long_load_transform = 0

[RearAxle]
kerb_strike_rejection = 0.0
oversteer_boost = 2.5210099220275879
power_slip_threshold = 0.10000000149011612
power_yaw_gain = 0.0
power_yaw_gamma = 0.5
power_yaw_punch = 0.05000000074505806
power_yaw_threshold = 0.20000000298023224
rear_align_effect = 0.66600000858306885
sop_effect = 1.6660000085830688
sop_scale = 1.0
sop_smoothing_factor = 0.0
sop_yaw_gain = 0.33300000429153442
unloaded_yaw_gain = 0.0
unloaded_yaw_gamma = 0.5
unloaded_yaw_punch = 0.05000000074505806
unloaded_yaw_sens = 1.0
unloaded_yaw_threshold = 0.20000000298023224
yaw_accel_smoothing = 0.0010000000474974513
yaw_kick_threshold = 0.0

[Safety]
gain_reduction = 0.30000001192092896
immediate_spike_threshold = 1500.0
slew_full_scale_time_s = 1.0
smoothing_tau = 0.20000000298023224
spike_detection_threshold = 500.0
stutter_safety_enabled = false
stutter_threshold = 1.5
window_duration = 0.0

[SlopeDetection]
alpha_threshold = 0.019999999552965164
confidence_enabled = true
confidence_max_rate = 0.10000000149011612
decay_rate = 5.0
enabled = false
g_slew_limit = 50.0
max_threshold = -2.0
min_threshold = -0.30000001192092896
sensitivity = 0.5
sg_window = 15
smoothing_tau = 0.039999999105930328
torque_sensitivity = 0.5
use_torque = true

[Vibration]
bottoming_enabled = true
bottoming_gain = 1.0
bottoming_method = 0
road_enabled = true
road_gain = 0.0
scrub_drag_gain = 0.0
slide_enabled = false
slide_freq = 1.0
slide_gain = 0.22656199336051941
spin_enabled = true
spin_freq_scale = 1.0
spin_gain = 0.5
texture_load_cap = 1.5
vibration_gain = 1.0